services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyper-captcha-resolver:latest
    container_name: hyper-captcha-resolver-web
    command: ["./run_web.sh", "start"]
    ports:
      - "5001:5000"
    environment:
      - HOST_PORT=5001
      - FLASK_ENV=production
      - CPU_ONLY=1
      - CAPTCHA_ID=gov24
      - BACKEND=pytorch
      - REV=1
      - IMAGE_WIDTH=200
      - IMAGE_HEIGHT=50
    restart: unless-stopped
    tty: true
networks:
  default:
    name: hyper-captcha-resolver-net
