services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyper-captcha-resolver:latest
    container_name: hyper-captcha-resolver-web
    ports:
      - "5001:8000"
    environment:
      - DEFAULT_CAPTCHA_ID=gov24
    volumes:
      - ./captcha_data:/app/captcha_data:ro
    restart: unless-stopped
networks:
  default:
    name: hyper-captcha-resolver-net
